-keep class com.alzahra.** { *; }
-keepattributes *Annotation*
-dontwarn org.telegram.**
-dontwarn org.apache.http.**
-dontwarn javax.inject.**
-keep class org.apache.http.** { *; }
-keep class org.telegram.** { *; }
-keepattributes Signature
-keepattributes Exceptions
